# Generated by Django 6.0.2 on 2026-04-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Rooms', 'Rooms'), ('Loanables', 'Loanables'), ('Tutoring', 'Tutoring')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('avail', models.CharField(choices=[('Available', 'Available'), ('Limited', 'Limited'), ('Unavailable', 'Unavailable')], max_length=20)),
            ],
        ),
    ]
